<?php if(!$this->getProducttabsCfg('enabled')) return;
$helper_cf = Mage::helper('producttabs');
$auto = $helper_cf->getProducttabsCfg('auto');
$speed = $helper_cf->getProducttabsCfg('speed');
$itemsDefault = $helper_cf->getProducttabsCfg('itemsDefault');
$itemsDesktop = $helper_cf->getProducttabsCfg('itemsDesktop');
$itemsDesktopSmall = $helper_cf->getProducttabsCfg('itemsDesktopSmall');
$itemsTablet = $helper_cf->getProducttabsCfg('itemsTablet');
$itemsMobile = $helper_cf->getProducttabsCfg('itemsMobile');
$next_back = $helper_cf->getProducttabsCfg('next_back');
$nav_ctrl = $helper_cf->getProducttabsCfg('nav_ctrl');

$product_bestsellers = $helper_cf->getProductCfg('product_bestsellers');
$product_featured = $helper_cf->getProductCfg('product_featured');
$product_mostviewed = $helper_cf->getProductCfg('product_mostviewed');
$product_new = $helper_cf->getProductCfg('product_new');
$product_random = $helper_cf->getProductCfg('product_random');
$product_sale = $helper_cf->getProductCfg('product_sale');


$default = $this->getTypeDefault();
$_tabs = $this->getTabs();
$numtab =count($_tabs);
if($numtab){
?>
	<div class="producttabs"> 
		<?php				
			if ( !$this->getProducttabsCfg('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getProducttabsCfg('width_thumbnail');
			}
			if( !$this->getProducttabsCfg('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getProducttabsCfg('height_thumbnail');
			}
		?>
		<h2 class ="title-producttabs"><?php echo $this->__($this->getProducttabsCfg('title'))?></h2>
		<div class="tab-container">
			<ul id="producttabs">
				<?php
					$i=1;
					foreach ($_tabs as $type =>$name) {
					if($i==1){ $oder = ' first active'; }else if($i== $numtab){ $oder=" last";}else {$oder="";}
					$i++;
					echo '<li class="item' .$oder.'"><h3 class ="'.$type.'">'.$name.'</h3></li>';
					}
				?>
			</ul>
		</div>
		
		<div class="content">
			<?php
				$i=1;
				foreach($_tabs as $type =>$name)
				{
				?>
					<div id="producttab_<?php echo $type ?>"  class="tab <?php if($i==1) echo 'active' ?>">
					<?php
					$i++;
					switch ($type) {
						case 'bestseller':
							$_productCollection = $this->getBestsellers();
							break;		
						case 'featured':
							$_productCollection = $this->getFeatured();
							break;
						case 'mostviewed':
							$_productCollection = $this->getMostviewed();
							break;
						case 'new':
							$_productCollection = $this->getNew();
							break;
						case 'random':
							$_productCollection = $this->getRandom();
							break;
						case 'sale':
							$_productCollection = $this->getSale();
							break;
					}
					?>
					<?php
						$_helper = $this->helper('catalog/output');
					?>
					<?php if(!$_productCollection->count()): ?>
					<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
					<?php else: ?>
					<div class="mage-products">
						<?php
						$width = Mage::getStoreConfig('producttabs/producttabs_config/width_thumbnail'); 
						$height = Mage::getStoreConfig('producttabs/producttabs_config/height_thumbnail'); 
						?>

						<?php $_collectionSize = $_productCollection->count() ?>
						<?php
						$rows = Mage::getStoreConfig('producttabs/producttabs_config/row_show');
						?>
						<div class="owl-container">
							<div class="producttabs-products-owl">
								<?php $i=0; foreach ($_productCollection as $_product): ?>
									<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
									<?php if($i %$rows == 0) echo "<div class='item'>"; ?>
										<div class="item-inner">  
											<div class="images-container"> 
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
													<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
												</a>
												
											</div> 
											<div class="des-container"> 
												<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
												
												<?php
													if(Mage::getStoreConfig('producttabs/producttabs_config/show_price')):
												?>
													<div class="price-box">
														<?php
														$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
														$price = $_product->getPrice();
														$specialprice = $_product->getFinalPrice();
														if($price != $specialprice){
														if($price != ''){
														echo '<p class="old-price"><span class="price-label">';
														echo $this->__('Regular Price'). ': </span>';
														echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
														}
														if($specialprice != '')
														{
														echo '<p class="special-price">
														<span class="price-label">Special Price</span>
														<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
														</p> ';
														} 
														}else {
														echo '<div class="price-boxs">
														<span class="regular-price">
														<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
														</span>    
														</div>';    
														}
														?>
													</div>
												<?php endif; ?>
												<?php if(Mage::getStoreConfig('producttabs/producttabs_config/review')): ?>
													 <?php
													$storeId = Mage::app()->getStore()->getId();
													$summaryData = Mage::getModel('review/review_summary')
																		->setStoreId($storeId)
																		->load($_product->getId());
													if ($summaryData['rating_summary']):
													?>
														<div class="ratings">
															<div class="rating-box">  
																<div class="rating" style="width: <?php echo $summaryData['rating_summary'] ; ?>%;"></div>  
															</div>
															<span class="amount"><a onclick="var t = opener ? opener.window : window; t.location.href='<?php echo Mage::getUrl("review/product/list/id/".$_product->getId()) ?>'; return false;" href="#"><?php echo $summaryData['reviews_count'] ?> Review(s)</a></span>
														</div>
													<?php endif; ?>
												<?php endif; ?>
												<div class="actions"> 
													<?php if(Mage::getStoreConfig('producttabs/producttabs_config/addtocart')):?>
														<?php if($_product->isSaleable()): ?>
															<button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><em class="tooltip"><?php echo $this->__('add cart') ?></em><?php echo $this->__('Add to Cart') ?></span></span></button>
														<?php else: ?>
															<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
														<?php endif; ?>
													<?php endif; ?>
													<ul class="add-to-links">
														<?php if(Mage::getStoreConfig('producttabs/producttabs_config/addtowishlist')):?>
															<?php if ($this->helper('wishlist')->isAllow()) : ?>
																<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><em class="tooltip"><?php echo $this->__('wishlist') ?></em><?php echo $this->__('Add to Wishlist') ?></a></li>
															<?php endif; ?>
														<?php endif; ?>
														<?php if(Mage::getStoreConfig('producttabs/producttabs_config/addtocompare')):?>
															<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
																<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare "><em class="tooltip"><?php echo $this->__('wishlist') ?></em><?php echo $this->__('Add to Compare') ?></a></li>
															<?php endif; ?>
														<?php endif; ?>
													</ul> 
														
												</div>
												 
											</div>
												
										</div>	
									<?php $i++;?>
									<?php if($i %$rows == 0) echo "</div>"; ?> 
								<?php endforeach; ?>
									<?php if($i %$rows != 0) echo "</div>"; ?>
							</div>
						</div>
						
					</div>
					<?php endif; ?>
					</div>
				<?php
				}
			?>
		</div> 
	</div>
<script type="text/javascript">
	$jq(document).ready(function(){
		$jq(".producttabs-products-owl").owlCarousel({
			autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
			items : <?php if($itemsDefault) echo $itemsDefault; else echo '5'; ?>,
			itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
			itemsDesktopSmall : [991,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
			itemsTablet: [700,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
			itemsMobile : [400,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
			slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
			stopOnHover : true,
			pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
			scrollPerPage:true,
		});
		
		$jq('#producttabs li').click(function(){
			var pr_tab = $jq(this).find("h3").attr('class');
			$jq( "#producttabs li" ).removeClass( "active" );
			$jq(this).addClass( "active" );
			$jq("#producttab_"+pr_tab).slideDown(400).siblings().slideUp(400);
		});
	}); 
</script>
<?php
}
?>