<?php
$enabled_slide = Mage::getStoreConfig('blog/slide/enabled');
if($enabled_slide){
$numberrow = $this->getConfig('numberrow');
$speed = $this->getConfig('speed');
$auto = $this->getConfig('auto');
$itemsDefault = $this->getConfig('itemsDefault');
$itemsDesktop = $this->getConfig('itemsDesktop');
$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
$itemsTablet = $this->getConfig('itemsTablet');
$itemsMobile = $this->getConfig('itemsMobile');
$show_image = $this->getConfig('showimage');
$show_title = $this->getConfig('showtitle');
$show_author = $this->getConfig('showauthor');
$show_time = $this->getConfig('showtime');
$show_shortcontent = $this->getConfig('showshortcontent');
$showcomment = $this->getConfig('showcomment');
$show_readmore = $this->getConfig('showreadmore');
$next_back = $this->getConfig('next_back');
$nav_ctrl = $this->getConfig('nav_ctrl');
?>
<?php if ($posts = $this->getRecent()):  $i = 0;?>  
		<div class="menu-recent">
			<div class="container">
		
				<?php if(Mage::getStoreConfig('blog/blog/title')){?>
					<div class="blog-title group-title"><h2><?php echo Mage::getStoreConfig('blog/blog/title');?></h2></div>
				<?php }?>
				<div class="owl-container">
					<div class="owl">
					<?php foreach ($posts as $post): ?>
						<?php if($i % $numberrow == 0) echo '<div>'; ?>
							<div class="item-inner">  
								<div class="images-container"> 
									<?php if($show_image): ?>
										<?php if($post->getAddress()): ?><a href="<?php echo $post->getAddress(); ?>" ><?php endif; ?>
										<?php echo '<img alt="" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getThumbnailimage().'"/>'; ?>
										<?php if($post->getAddress()): ?></a><?php endif; ?>
									<?php endif; ?>
								</div>
								<div class="des-container">
									
									<div class="des">
										<?php if($show_title): ?> <a href="<?php echo $post->getAddress(); ?>" class="title-blog" ><?php echo '<span>'.$post->getTitle().'</span>' ?></a> <?php endif; ?>
								
										<?php if($show_shortcontent) echo strip_tags($this->getContentBlogSidebar($post->getShortContent(),150));?>
									 
									</div>
									<div class="date-comments">
										<?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
										<?php if($show_time) echo '<div class="time"><span class="date">'.date("F d, Y", $date).'</span></div>'; ?>
										<?php if($show_author) echo '<span class="author">'.$post->getUser().'</span>'; ?> 
									</div>
									<?php if($show_readmore): ?> <div class="readmore"><a href="<?php echo $post->getAddress(); ?>">Continue reading</a></div> <?php endif; ?>
								</div> 
									  
							</div>
						<?php 
						$i++;
						if($i % $numberrow == 0)echo '</div>';  ?>
						<?php endforeach; ?>
						<?php if($i % $numberrow != 0)echo '</div>'; ?>
					</div>
				</div> 
			</div> 
			
		</div>
	 <script type="text/javascript">
		$jq(document).ready(function(){
			$jq(".menu-recent .owl").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : <?php if($itemsDefault) echo $itemsDefault; else echo '5'; ?>,
				itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
				itemsDesktopSmall : [991,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
				itemsTablet: [700,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
				itemsMobile : [400,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true,
			});
		});
	</script>
<?php endif;
}
?>
