<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<div class="page-title">
    <h1>Blog</h1>
</div>

<?php echo $this->getChildHtml('magentothem_blog_comments_toolbar'); ?>
<?php $i=0; foreach ($posts as $post): ?>

    <div class="postWrapper <?php if( $i++ % 2==0 ) {echo 'one'; } else {echo 'two';}?> ">
		<div class="item-inner">
			<div class="row">
				<div class="col-sm-6 col-sms-6 col-smb-12">
					<div class="images-container">
						<?php if($post->getAddress()): ?><a href="<?php echo $post->getAddress(); ?>" ><?php endif; ?>
							<?php echo '<img alt="" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getThumbnailimage().'"/>'; ?>
						<?php if($post->getAddress()): ?></a><?php endif; ?>
						
						<?php $explode = explode('/', date($post->getCreatedTime())) ?>
						<?php $newformat = strtotime($explode[1].'/'.$explode[0].'/'.$explode[2]); ?>

						<div class="time">
							<span class="month"><?php echo $this->__(date("M", $newformat)) ?></span>
							<span class="date"><?php echo date("d", $newformat) ?></span>
						</div>
					</div>
					
				</div>
				<div class="col-sm-6 col-sms-6 col-smb-12">
					<div class="des-container"> 
						<div class="des">
							<div class="postTitle">
								<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2> 
							</div>
							<div class="post-by">
								<div class="post">
									<?php $postCats = $post->getCats(); ?>
									<?php if (!empty($postCats)): ?>
										<?php echo Mage::helper('blog')->__('Posted in'); ?>
										<?php foreach ($postCats as $data): ?>
											<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
										<?php endforeach; ?>
									<?php else: ?>
										<?php echo Mage::helper('blog')->__('Posted'); ?>
									<?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
								</div>	
								
							</div>
							
								
							<div class="postContent"><?php echo $post->getPostContent(); ?></div>

							<?php echo $this->getBookmarkHtml($post) ?>
							<div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
							<div class="postDetails">
								<?php if ($this->getCommentsEnabled()): ?>
									<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a>
								<?php endif; ?>
								
							</div>
						</div>
					</div>
					
				</div>
				
			</div>
		</div>
		 
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('magentothem_blog_comments_toolbar'); ?>
