<?php
$title = $this->getTitle();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<?php	
		$itemsDefault = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/itemsDefault'); 
		$itemsDesktop = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/itemsDesktop');
		$itemsDesktopSmall = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/itemsDesktopSmall');
		$itemsTablet = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/itemsTablet');
		$itemsMobile = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/itemsMobile');
        $speed = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/speed');
        $nav_ctrl = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/nav_ctrl');
        $next_back = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/next_back');
        $show_price = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/show_price');
        $review = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/show_review');
        $rows = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/row_show');
		$title = $this->getTitle();
?>
<div class="category-tabslider">
<?php 	echo '<div class="title-cate"><h2>'.$title.'</h2></div>'; ?>
  <ul class="tabs tabs<?php echo '-'.$identify;?>  tab_categorys"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model = Mage::getModel('catalog/category');
		$cateName = $cate_model->load($cate_id)->getName();
		
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?> tab<?php echo $cate_id.'-'.$identify;?>"><?php  echo $cateName; ?></li>
	<?php }  $k++; } ?>
    </ul>

	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) {
		?>
		 <div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
			<div class="owl-container">
				<div class="owl">	
				<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php if($i %$rows == 0) echo "<div class='categorytab-item item'>"; ?>
					<div class="item-inner">
						<div class="images-container">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
						</div>
						<div class="des-container">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php if($review) { ?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php } ?>
							<?php if( $this->getConfig('show_price') ): ?>
								<div class="price-box">
									<?php
									$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
									$price = $_product->getPrice();
									$specialprice = $_product->getFinalPrice();
									if($price != $specialprice){
									if($price != ''){
									echo '<p class="old-price"><span class="price-label">';
									echo $this->__('Regular Price'). ': </span>';
									echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
									}
									if($specialprice != '')
									{
									echo '<p class="special-price">
									<span class="price-label">Special Price</span>
									<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
									</p> ';
									} 
									}else {
									echo '<div class="price-boxs">
									<span class="regular-price">
									<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
									</span>    
									</div>';    
									}
									?>
								</div>
							<?php endif; ?>
							<div class="actions">
								<?php if($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><em class="tooltip"><?php echo $this->__('add cart') ?></em><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><em class="tooltip"><?php echo $this->__('wishlist') ?></em><?php echo $this->__('Add to Wishlist') ?></a></li>
									<?php endif; ?>
									<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><em class="tooltip"><?php echo $this->__('compare') ?></em><?php echo $this->__('Add to Compare') ?></a></li>
									<?php endif; ?>
								</ul> 
							</div>
						
						</div>
					<?php $i++;?>
					</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                   
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>
				</div>	
			</div>
			<script type="text/javascript">
				$jq(document).ready(function(){
					<?php $idBx = '#tab'.$cate_id.'-'.$identify.' .owl'; ?>
					$jq("<?php echo $idBx; ?>").owlCarousel({
						autoPlay : false,
						items : <?php if($itemsDefault) echo $itemsDefault; else echo '5'; ?>,
						itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
						itemsDesktopSmall : [991,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
						itemsTablet: [700,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
						itemsMobile : [400,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
						slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
						navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
						stopOnHover : true,
						pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
					});
				});
			</script>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->

<script type="text/javascript">

$jq(document).ready(function() {
	
	$jq(".tab_content_<?php echo $identify; ?>").hide();
	$jq(".tab_content_<?php echo $identify; ?>:first").show(); 

	$jq("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
		$jq("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
		$jq(this).addClass("active");
		$jq(".tab_content_<?php echo $identify; ?>").hide();
		var activeTab = $jq(this).attr("class"); 
		$jq("#"+activeTab).fadeIn(); 
	});
});

</script> 
